// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbgmqyqrspbjzyulutch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiZ21xeXFyc3Bianp5dWx1dGNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMjMyNDQsImV4cCI6MjA1ODc5OTI0NH0.-i8erVkRF-9RcWvo9nvawBvGOiB5o0POJbqIXmraVzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);